version: 0.1

# Notes: ARN references within the associated SAM template to some resources are defined
# by naming convention, not by Reference, to avoid circular references. GovCloud ARNs use
# a different scheme name 'aws-us-gov' instead of 'aws'.
# For example, a reference to an ALB Target Group in commercial (local) deployment is:
# arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/project-cies-doc-local/*
# whereas in the GovCloud dev deployment it becomes:
# arn:aws-us-gov:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/project-cies-doc-dev/*
#
# ALBVisibility determines whether the ALB is internet facing or only accessible from a VPC. For all deployment
# except for local testing this value MUST be 'internal'. For 'local' deployment the value may be internet-facing,
# in which case adding WAF that restricts access to only the developer IP to the ALB is highly recommended. External
# IPs in the AWS range will be probed within minutes of endpoint creation.

prprd:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            stack_name: 'spi-ocr-app-prprd'
            s3_prefix: 'spi-ocr-app-prprd'
            disable_rollback: false
            parameter_overrides:
            - LogLevel=INFO
            - ALBVisibility=internal
            
prod:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            stack_name: 'spi-ocr-app-prod'
            s3_prefix: 'spi-ocr-app-prod'
            disable_rollback: false
            parameter_overrides:
            - LogLevel=INFO
            - ALBVisibility=internal

# NOTE, the (ephemeral) dev environments parameters are defined as "default"
# because the environment name is different for each dev environment
# Environments will be created with stack names like "dev-712532176", resources
# in the dev environments follow a similar naming convention
default:
    deploy:
        parameters:
            resolve_s3: false
            disable_rollback: false
            capabilities: CAPABILITY_IAM
            # stack-name MUST be provided externally
            # s3-bucket MUST be provided externally
            # VPC MUST be provided externally
            # AlbServiceRoleAccount MUST be provided externally
            # subnets MUST be provided externally
            # networkInterfaceSubnet MUST be provided externally
            # ARNScheme MUST be provided externally
            parameter_overrides:
                - LogLevel=DEBUG
                - stage=dev

