version: 0.1

dev:
    deploy:
        parameters:
            stack_name: 'spi-ocr-app-infrastructure-dev'
            s3_bucket: cies-bipp-infrastructure-dev
            resolve_s3: false
            s3_prefix: 'spi-ocr-app-dev'
            region: 'us-east-1'
            Stage: 'dev'
            confirm_changeset: true
            capabilities: CAPABILITY_NAMED_IAM
            disable_rollback: false
            parameter_overrides: stage=dev

prprd:
    deploy:
        parameters:
            stack_name: 'spi-ocr-app-infrastructure-prprd'
            s3_bucket: cies-bipp-infrastructure-prprd
            resolve_s3: false
            s3_prefix: 'spi-ocr-app-prprd'
            region: 'us-east-1'
            Stage: 'prprd'
            confirm_changeset: true
            capabilities: CAPABILITY_NAMED_IAM
            disable_rollback: false
            parameter_overrides: stage=prprd

prod:
    deploy:
        parameters:
            stack_name: 'spi-ocr-app-infrastructure-prod'
            s3_bucket: cies-bipp-infrastructure-prod
            resolve_s3: false
            s3_prefix: 'spi-ocr-app-prod'
            region: 'us-east-1'
            Stage: 'prod'
            confirm_changeset: true
            capabilities: CAPABILITY_NAMED_IAM
            disable_rollback: false
            parameter_overrides: stage=prod
